#!/bin/sh

export USER="USER___REPLACE"
export HOME="HOME___REPLACE"

fix_ownership() {
  chown -R USER___REPLACE:USER___REPLACE "PROJECT_ROOT___REPLACE"
}
check_exit_status() {
  [ $1 -eq 0 ] || { fix_ownership; exit 1; }
}

cd "PROJECT_ROOT___REPLACE" && ./scripts/export.sh --schedule=schedule___REPLACE
check_exit_status $?

su USER___REPLACE -c 'cd "PROJECT_ROOT___REPLACE" && ./scripts/git/push.sh --schedule=schedule___REPLACE'

fix_ownership
